apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-argocd-app
  namespace: argocd
spec:
  project: First_Project
  source:
    repoURL: https://github.com/vijayjirange/argocd-example-apps.git
    targetRevision: master
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: default
